export { grep } from "./tools"
export { runRg, runRgCount } from "./cli"
export { resolveGrepCli, resolveGrepCliWithAutoInstall } from "./constants"
export { downloadAndInstallRipgrep, getInstalledRipgrepPath } from "./downloader"
export type { GrepResult, GrepMatch, GrepOptions, CountResult } from "./types"
